services:
  - type: web
    name: p2603-calculadora-ciclo-vida-tuberia
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 1 -k uvicorn.workers.UvicornWorker webapp.main:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
    healthCheckPath: /health
